meta_product_name: "Safe Bite"
meta_title: "Safe Bite - Safe Bite is an app to help you eat safe, fast!"
meta_description: "Safe Bite is an app to help you eat safe, fast!"
meta_image: "cover-picture.jpg" # should exist in `app/assets/images/`
